### ISSUE TITLE
Change name of AreEquatable to something else

### ISSUE THREAD

**Issue by konkked** [konkked/Underscore.cs#48]
doesn't do what someone would expect if the object ( use methods provided by IEquatable to check for equality ) should change the name to something else...

Suggestions?

Think `_.Object.SoftEquals(a,b)` might be okay, not sure if "Soft Equals" is exactly clear.

**Comment by zckeyser** [comment]
I think there's a limit to how clear we can be with the name -- I'd probably opt for `_.Object.AreEquivalent(a, b)` but I'm okay with SoftEquals too

**Comment by konkked** [comment]
Okay, let's change the name to `_.Object.AreEquivalent` then
