### ISSUE TITLE
Decide Intellisense code comment strategy

### ISSUE THREAD

**Issue by konkked** [konkked/Underscore.cs#49]
Should we be commenting for Intellisense on everything? Even if it is not meant to be publically accessible?

We can do it but just takes a lot of time.

Maybe we can come up with a script or something that puts comments in the signature of methods that implement an interface?

**Comment by zckeyser** [comment]
I don't think it's really necessary -- more effort than it's worth. Typically a dev is going to be reaching the implementation through the interface anyways.
