### ISSUE TITLE
Consider making this some form of a LINQ extension. 

### ISSUE THREAD

**Issue by AdamHess** [konkked/Underscore.cs#54]
A lot of what underscore does is manipulating lists of items, this project could be an incredible powerhouse if it works as an extension to LINQ as to acting on list, arrays and other enumerable types.

**Comment by zckeyser** [comment]
I'd probably opt to add that in addition to having the _ entry point for list operations, but I think that's a good idea. I'd be willing to do the porting for that, though I'd like to get the opinion of @konkked since he controls the NuGet repository.

**Comment by zckeyser** [comment]
Put up a PR with these changes, waiting on @konkked to check out/approve the PR

**Comment by zckeyser** [comment]
Merged the PR, once @konkked gives me NuGet repo permissions I'll put it up on the actual package.

**Comment by zckeyser** [comment]
The NuGet package including this has been uploaded as version 1.0.0
