### ISSUE TITLE
Add _.Map and _.Reduce

### ISSUE THREAD

**Issue by AdamHess** [konkked/Underscore.cs#56]
It may be Asinine, but .Select is not clear that it can (and often is) used as a Map function. 

Additionally, Aggregate is a little clearer that it's a reducing function but is not using the same naming convention as Underscore "reduce" 

Together both of these APIs will make developers who go from JavaScript Underscore -> C# Underscore a little more seamless.

**Comment by zckeyser** [comment]
Makes sense to me -- I'll tack it onto my object documentation branch.

**Comment by zckeyser** [comment]
Added -- will put in NuGet once I can

**Comment by zckeyser** [comment]
The NuGet package including this has been released as version 1.0.0
