### ISSUE TITLE
Incorrect behavior of Throttle and Debounce

### ISSUE THREAD

**Issue by rqx110** [konkked/Underscore.cs#58]
the Debounce will run many time for every internal time, it's not correct.

Maybe you can follow this repository [https://github.com/zpbappi/underscore-net](https://github.com/zpbappi/underscore-net), it has correct behavior.

**Comment by rqx110** [comment]
sorry, it's my fault!

**Comment by zckeyser** [comment]
Another note on this is that their implementation uses a simple mutex implementation, the implementation is intentionally lockless.
